name: CI

on:
    push:
    pull_request:
        types: [opened, reopened]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v6
            - name: Run "composer test" script
              run: composer test
